//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TowerDefense
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enemy
    {
        public int Id { get; set; }
        public int Level { get; set; }
        public int HP { get; set; }
        public int Speed { get; set; }
    
        public virtual EnemyType Type { get; set; }
    }
}
