//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TowerDefense
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enemy> Enemies { get; set; }
        public virtual DbSet<EnemyType> EnemyTypes { get; set; }
        public virtual DbSet<Tower> Towers { get; set; }
        public virtual DbSet<TowerType> TowerTypes { get; set; }
        public virtual DbSet<World> Worlds { get; set; }
        public virtual DbSet<CellType> CellTypes { get; set; }
    }
}
