//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TowerDefense
{
    using System;
    using System.Collections.Generic;

    public  enum Cell
    {
        Wall,
        Open
    } 
    
    public partial class World
    {
        public int Id { get; set; }
        public int Sequence { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    
        public virtual CellType Type { get; set; }
    }
}
